server:
  port: 9090

spring:
  application:
    name: university-service
  cloud:
    gateway:
      routes:
        - id: student-service
          uri: http://localhost:8080
          predicates:
            - Path=/student-service/**
          filters:
            - RewritePath=/student-service/(?<segment>.*), /api/v1/$\{segment}

